name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # Build with Maven
    - name: Build application
      run: mvn clean compile

    # Run the application
    - name: Run application
      run: java -cp target/classes com.example.HelloWorld
